services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_trace
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATASOURCE: "jdbc:postgresql://localhost:5432/money_trace"
    depends_on:
      - postgres
